name: Continuous integration

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # go ahead and install .net on runner
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish artifacts
#        working-directory: src/
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts # publish only api project and output it in artifacts folder
        # src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj - usually this is the entry point of your application

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifacts/
