name: Continuous integration

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # go ahead and install .net on runner
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish artifacts
#        working-directory: src/
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts # publish only api project and output it in artifacts folder
        # src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj - usually this is the entry point of your application

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: artifacts2/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure App service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-github-actions
          package: artifacts2/
