name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: read

jobs:
  cron:
    name: cron job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"
