name: Run every 1 hour

on:
  schedule:
    - cron: '@hourly'

permissions:
  contents: read

jobs:
  cron:
    name: cron job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world"
