name: Secrets workflow

on:
  pull_request:
    branches:
      - main

env:
  API_CSPROJ_PATH: ./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj

permissions:
  contents: read

jobs:
  secrets:
    name: Secrets job
    runs-on: ubuntu-latest
    env:
      JOB_NAME: secret-job

    steps:
      - name: Hello world
        run: echo "The job name is $JOB_NAME and the API csproj path is $API_CSPROJ_PATH"

  some_new_job:
    name: Some new job
    runs-on: ubuntu-latest
    env:
      JOB_NAME: new-job

    steps:
      - name: Hello world
        run: echo "The job name is $JOB_NAME and the API csproj path is $API_CSPROJ_PATH"

  secret_job:
    name: Secret job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "My secret is ${{ secrets.SECRET_KEY }}"
