name: Secrets workflow

on:
  pull_request:
    branches:
      - main

env:
  API_CSPROJ_PATH: ./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj

permissions:
  contents: read

jobs:
  secrets:
    name: Secrets job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "$API_CSPROJ_PATH"
