name: "Step - Deploy"
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
# we need the secrets here, but we will inherit them from repository secrets
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
        description: "This is azure tenant id"

jobs:
  deploy:
    name: Deploy ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: artifacts2/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure App service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-github-actions-${{ inputs.env }}
          package: artifacts2/
